version: '3'

services:
  php:
    build:
      context: .
      dockerfile: ./docker-sanjo/Dockerfile
    container_name: php-sanjo
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
  postgres:
    image: postgres
    container_name: postgres-sanjo
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sanjo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-sanjo
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker-sanjo/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres


